name: data-quality-and-transform
on:
  push:
  pull_request:

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r pipeline/requirements.txt
      - name: Run unit tests
        run: |
          pytest -q
      - name: Run pipeline (smoke)
        run: |
          python pipeline/run_pipeline.py --input_dir data/raw --output_dir warehouse --reports_dir reports
